In [1]:
import torch
inputs=torch.tensor(
    [
        [0.43,0.15,0.89],#your (x^1)
        [0.55,0.87,0.66],#journey (x^2)
        [0.57,0.85,0.64],#starts (x^3)
        [0.22,0.58,0.33],#with (x^4)
        [0.77,0.25,0.10],#one (x^5)
        [0.05,0.80,0.55]# step (x^6)
    ]
)

In [2]:
input_query=inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [3]:
input_1=inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [4]:
torch.dot(input_query,input_1)

tensor(0.9544)

In [7]:
res=0
for idx,ele in enumerate(inputs[0]):
    res+=inputs[0][idx]*input_query[idx]

print(res)

tensor(0.9544)


In [8]:
query=inputs[1]
attention_scores_2=torch.empty(inputs.shape[0])
for i,x_i in enumerate(inputs):
    attention_scores_2[i]=torch.dot(x_i,input_query)
print(attention_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [9]:
attention_weight_2=attention_scores_2/attention_scores_2.sum()

In [10]:
attention_weight_2

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [11]:
attention_weight_2.sum()

tensor(1.0000)

In [12]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

In [15]:
softmax_naive(attention_scores_2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [17]:
query=inputs[1]
context_vec_2=torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    context_vec_2+=attention_weight_2[i]*x_i
print(context_vec_2)

tensor([0.4355, 0.6451, 0.5680])


In [19]:
attention_scores=torch.empty(6,6)
for i,x_i in enumerate(inputs):
    for j,x_j in enumerate(inputs):
        attention_scores[i,j]=torch.dot(x_i,x_j)
print(attention_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [23]:
attention_scores=inputs@inputs.T
print(attention_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [25]:
attention_weights=torch.softmax(attention_scores,dim=1)
print(attention_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [26]:
attention_weights.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [27]:
all_context_vecs=attention_weights@inputs
print(all_context_vecs)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [28]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [31]:
x_2=inputs[1]
d_in=inputs.shape[1]
d_out=2
print(x_2)
print(d_in)
print(d_out)

tensor([0.5500, 0.8700, 0.6600])
3
2


In [35]:
torch.manual_seed(123)
w_query=torch.nn.Parameter(torch.rand(d_in,d_out))
w_key=torch.nn.Parameter(torch.rand(d_in,d_out))
w_value=torch.nn.Parameter(torch.rand(d_in,d_out))


In [36]:
w_query

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]], requires_grad=True)

In [37]:
w_key

Parameter containing:
tensor([[0.1366, 0.1025],
        [0.1841, 0.7264],
        [0.3153, 0.6871]], requires_grad=True)

In [38]:
w_value

Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]], requires_grad=True)

In [39]:
query_2=x_2@w_query

In [40]:
query_2

tensor([0.4306, 1.4551], grad_fn=<SqueezeBackward4>)

In [41]:
keys=inputs@w_key
keys

tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]], grad_fn=<MmBackward0>)

In [43]:
values=inputs@w_value
values

tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]], grad_fn=<MmBackward0>)

In [44]:
keys_2=keys[1]
attention_score_2=keys_2@query_2
print(attention_score_2)

tensor(1.8524, grad_fn=<DotBackward0>)


In [45]:
queries=inputs@w_query
queries

tensor([[0.2309, 1.0966],
        [0.4306, 1.4551],
        [0.4300, 1.4343],
        [0.2355, 0.7990],
        [0.2983, 0.6565],
        [0.2568, 1.0533]], grad_fn=<MmBackward0>)